# Intro

In [65]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn import set_config

In [66]:
set_config(transform_output="pandas")

# Dummy data

In [67]:
dummy_data = [[1, 2, 3, 10, 11, 12], [40, 50, 60, 130, 140, 100]]

X = pd.DataFrame(data=dummy_data).T.rename(columns={0: "Var1", 1: "Var2"})
X

   Var1  Var2
0     1    40
1     2    50
2     3    60
3    10   130
4    11   140
5    12   100

# StandardScaler de scikit-learn

In [68]:
scaler = StandardScaler()

In [69]:
scaler.fit(X)

StandardScaler()

In [70]:
scaler.mean_

array([ 6.5       , 86.66666667])

In [71]:
scaler.var_

array([  20.91666667, 1522.22222222])

In [72]:
X_scaler = scaler.transform(X)

In [73]:
X_scaler

       Var1      Var2
0 -1.202587 -1.196101
1 -0.983935 -0.939793
2 -0.765283 -0.683486
3  0.765283  1.110665
4  0.983935  1.366972
5  1.202587  0.341743

In [74]:
X_scaler.describe().round(1)

       Var1  Var2
count   6.0   6.0
mean   -0.0  -0.0
std     1.1   1.1
min    -1.2  -1.2
25%    -0.9  -0.9
50%     0.0  -0.2
75%     0.9   0.9
max     1.2   1.4

In [75]:
scaler.fit_transform(X)

       Var1      Var2
0 -1.202587 -1.196101
1 -0.983935 -0.939793
2 -0.765283 -0.683486
3  0.765283  1.110665
4  0.983935  1.366972
5  1.202587  0.341743

# La misma transformación usando pandas

In [76]:
mean_ = X.mean()

In [77]:
var_ = X.var(ddof=0)

In [78]:
X_pandas = (X - mean_) / (var_**0.5)

In [79]:
X_scaler

       Var1      Var2
0 -1.202587 -1.196101
1 -0.983935 -0.939793
2 -0.765283 -0.683486
3  0.765283  1.110665
4  0.983935  1.366972
5  1.202587  0.341743

In [80]:
X_pandas

       Var1      Var2
0 -1.202587 -1.196101
1 -0.983935 -0.939793
2 -0.765283 -0.683486
3  0.765283  1.110665
4  0.983935  1.366972
5  1.202587  0.341743

# Nuestro propio Transformer

In [81]:
class MyCustomScaler:

    def fit(self, X):

        mean_ = X.mean()
        var_ = X.var(ddof=0)

        print(mean_)
        print(var_)

        self.mean_ = mean_
        self.var_ = var_

        return self

    def transform(self, X):

        Xt = (X - self.mean_) / (self.var_**0.5)

        return Xt

In [82]:
my_scaler = MyCustomScaler()

In [83]:
my_scaler.fit(X=X)

Var1     6.500000
Var2    86.666667
dtype: float64
Var1      20.916667
Var2    1522.222222
dtype: float64

In [84]:
my_scaler.mean_

Var1     6.500000
Var2    86.666667
dtype: float64

In [85]:
my_scaler.var_

Var1      20.916667
Var2    1522.222222
dtype: float64

In [86]:
X_my_scaler = my_scaler.transform(X=X)

In [87]:
X_my_scaler

       Var1      Var2
0 -1.202587 -1.196101
1 -0.983935 -0.939793
2 -0.765283 -0.683486
3  0.765283  1.110665
4  0.983935  1.366972
5  1.202587  0.341743

# Explicación del `__init__`

In [88]:
# dunder -> double underscore

# __new__
# __add__
# __init__

In [89]:
class MyCustomScaler:

    def __init__(self, verbose):
        self.verbose = verbose

    def fit(self, X):

        mean_ = X.mean()
        var_ = X.var(ddof=0)

        if self.verbose:
            print(mean_)
            print(var_)

        self.mean_ = mean_
        self.var_ = var_

        return self

    def transform(self, X):

        Xt = (X - self.mean_) / (self.var_**0.5)

        return Xt

In [90]:
my_scaler = MyCustomScaler(verbose=False)

In [91]:
my_scaler.fit(X)

# Herencia con dummy Mixin

In [92]:
class MyTransformerMixin:

    def fit_transform(self, X):

        print("Hello from MyTransformerMixin")
        Xt = self.fit(X=X).transform(X=X)

        return Xt

In [93]:
class MyCustomScaler2(MyTransformerMixin):

    def __init__(self, verbose):
        self.verbose = verbose

    def fit(self, X):

        mean_ = X.mean()
        var_ = X.var(ddof=0)

        if self.verbose:
            print(mean_)
            print(var_)

        self.mean_ = mean_
        self.var_ = var_

        return self

    def transform(self, X):

        Xt = (X - self.mean_) / (self.var_**0.5)

        return Xt

In [94]:
my_scaler2 = MyCustomScaler2(verbose=True)

In [95]:
my_scaler2.fit_transform(X=X)

Hello from MyTransformerMixin
Var1     6.500000
Var2    86.666667
dtype: float64
Var1      20.916667
Var2    1522.222222
dtype: float64

       Var1      Var2
0 -1.202587 -1.196101
1 -0.983935 -0.939793
2 -0.765283 -0.683486
3  0.765283  1.110665
4  0.983935  1.366972
5  1.202587  0.341743

# Herencia con TransformerMixin y BaseEstimator

In [97]:
from sklearn.base import TransformerMixin, BaseEstimator

In [98]:
class MyCustomScaler(BaseEstimator, TransformerMixin):

    def __init__(self, verbose):
        self.verbose = verbose

    def fit(self, X):

        mean_ = X.mean()
        var_ = X.var(ddof=0)

        if self.verbose:
            print(mean_)
            print(var_)

        self.mean_ = mean_
        self.var_ = var_

        return self

    def transform(self, X):

        Xt = (X - self.mean_) / (self.var_**0.5)

        return Xt

In [99]:
my_scaler = MyCustomScaler(verbose=True)

In [100]:
# <__main__.MyCustomScaler at 0x129325900>
my_scaler

MyCustomScaler(verbose=True)

In [101]:
my_scaler.fit_transform(X)

Var1     6.500000
Var2    86.666667
dtype: float64
Var1      20.916667
Var2    1522.222222
dtype: float64

       Var1      Var2
0 -1.202587 -1.196101
1 -0.983935 -0.939793
2 -0.765283 -0.683486
3  0.765283  1.110665
4  0.983935  1.366972
5  1.202587  0.341743

# Explicación del self

In [102]:
class MyCustomScaler(BaseEstimator, TransformerMixin):

    def __init__(self, verbose):
        self.verbose = verbose

    def fit(self, X):

        mean_ = X.mean()
        var_ = X.var(ddof=0)

        if self.verbose:
            print(mean_)
            print(var_)

        self.mean_ = mean_
        self.var_ = var_

        return self

    def transform(self, X):

        Xt = (X - self.mean_) / (self.var_**0.5)

        return Xt

In [112]:
my_scaler = MyCustomScaler(verbose=False)
my_scaler2 = MyCustomScaler(verbose=True)

In [109]:
try:
    my_scaler.fit(None, X)
except Exception as e:
    print(e)

MyCustomScaler.fit() takes 2 positional arguments but 3 were given

In [110]:
my_scaler.fit(X)

MyCustomScaler(verbose=False)

In [113]:
MyCustomScaler.fit(self=my_scaler, X=X)

MyCustomScaler(verbose=False)

In [114]:
MyCustomScaler.fit(self=my_scaler2, X=X)

Var1     6.500000
Var2    86.666667
dtype: float64
Var1      20.916667
Var2    1522.222222
dtype: float64

MyCustomScaler(verbose=True)

# Recap

In [115]:
class MyCustomScaler(BaseEstimator, TransformerMixin):

    def __init__(self, verbose):
        self.verbose = verbose

    def fit(self, X):

        mean_ = X.mean()
        var_ = X.var(ddof=0)

        if self.verbose:
            print(mean_)
            print(var_)

        self.mean_ = mean_
        self.var_ = var_

        return self

    def transform(self, X):

        Xt = (X - self.mean_) / (self.var_**0.5)

        return Xt