# Imports

In [1]:
import pandas as pd

from sklearn import set_config
from sklearn.preprocessing import StandardScaler

In [2]:
set_config(transform_output="pandas")

# Dummy data

In [3]:
dummy_data = [[1, 2, 3, 10, 11, 12], [40, 50, 60, 130, 140, 100]]

X = pd.DataFrame(data=dummy_data).T.rename(columns={0: "Var1", 1: "Var2"})
X

   Var1  Var2
0     1    40
1     2    50
2     3    60
3    10   130
4    11   140
5    12   100

# StandardScaler de scikit-learn

In [4]:
scaler = StandardScaler()

In [5]:
scaler.fit(X)

StandardScaler()

In [6]:
scaler.mean_

array([ 6.5       , 86.66666667])

In [7]:
scaler.var_

array([  20.91666667, 1522.22222222])

In [8]:
Xt_scaler = scaler.transform(X)

In [9]:
Xt_scaler

       Var1      Var2
0 -1.202587 -1.196101
1 -0.983935 -0.939793
2 -0.765283 -0.683486
3  0.765283  1.110665
4  0.983935  1.366972
5  1.202587  0.341743

In [10]:
Xt_scaler.describe().round(2)

       Var1  Var2
count  6.00  6.00
mean  -0.00 -0.00
std    1.10  1.10
min   -1.20 -1.20
25%   -0.93 -0.88
50%    0.00 -0.17
75%    0.93  0.92
max    1.20  1.37

# La misma transformación de pandas

In [11]:
mean_ = X.mean()

In [12]:
mean_

Var1     6.500000
Var2    86.666667
dtype: float64

In [13]:
var_ = X.var(ddof=0)

In [14]:
var_

Var1      20.916667
Var2    1522.222222
dtype: float64

In [15]:
Xt_pandas = (X - mean_) / (var_**0.5)

In [16]:
Xt_pandas

       Var1      Var2
0 -1.202587 -1.196101
1 -0.983935 -0.939793
2 -0.765283 -0.683486
3  0.765283  1.110665
4  0.983935  1.366972
5  1.202587  0.341743

In [17]:
pd.concat([Xt_scaler.describe().round(2), Xt_pandas.describe().round(2)], axis=1)

       Var1  Var2  Var1  Var2
count  6.00  6.00  6.00  6.00
mean  -0.00 -0.00 -0.00 -0.00
std    1.10  1.10  1.10  1.10
min   -1.20 -1.20 -1.20 -1.20
25%   -0.93 -0.88 -0.93 -0.88
50%    0.00 -0.17  0.00 -0.17
75%    0.93  0.92  0.93  0.92
max    1.20  1.37  1.20  1.37

# Nuestro propio Transformer

In [18]:
from sklearn.base import TransformerMixin, BaseEstimator

In [19]:
class MyStandardScaler(BaseEstimator, TransformerMixin):

    def __init__(self, verbose):
        self.verbose = verbose

    def fit(self, X):

        mean = X.mean()
        var = X.var(ddof=0)

        if self.verbose:
            print(mean)
            print(var)

        self.mean_ = mean
        self.var_ = var

        return self

    def transform(self, X):

        Xt = (X - self.mean_) / (self.var_**0.5)

        return Xt

In [20]:
my_scaler = MyStandardScaler(verbose=False)

In [21]:
my_scaler.fit(X)

MyStandardScaler(verbose=False)

In [22]:
my_scaler.mean_

Var1     6.500000
Var2    86.666667
dtype: float64

In [23]:
my_scaler.var_

Var1      20.916667
Var2    1522.222222
dtype: float64

In [24]:
Xt_myscaler = my_scaler.transform(X)

In [25]:
Xt_myscaler

       Var1      Var2
0 -1.202587 -1.196101
1 -0.983935 -0.939793
2 -0.765283 -0.683486
3  0.765283  1.110665
4  0.983935  1.366972
5  1.202587  0.341743

In [26]:
pd.concat(
    [
        Xt_scaler.describe().round(2),
        Xt_pandas.describe().round(2),
        Xt_myscaler.describe().round(2),
    ],
    axis=1,
)

       Var1  Var2  Var1  Var2  Var1  Var2
count  6.00  6.00  6.00  6.00  6.00  6.00
mean  -0.00 -0.00 -0.00 -0.00 -0.00 -0.00
std    1.10  1.10  1.10  1.10  1.10  1.10
min   -1.20 -1.20 -1.20 -1.20 -1.20 -1.20
25%   -0.93 -0.88 -0.93 -0.88 -0.93 -0.88
50%    0.00 -0.17  0.00 -0.17  0.00 -0.17
75%    0.93  0.92  0.93  0.92  0.93  0.92
max    1.20  1.37  1.20  1.37  1.20  1.37